#!/bin/sh

echo "*** RESIIST Demonstrator ***"
echo "*** Simulation (real type) as data sources ***"
echo "*** Evolution function: Random with inital manual value ***"

java -jar gmm-poc-resiist-0.0.1Simulation-SNAPSHOT.jar credentials.csv configuration.csv dataSourceSimulation.csv
